---
- name: Fetch Latest Maven.
  uri:
    url: "https://apache.claz.org/maven/maven-3/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz"
    method: GET
    follow_redirects: safe
    dest: "{{ tmp_dir }}"
  register: fetch_response

- name: Create Installation Directory.
  file:
    path: "{{ mvn_install_dir }}"
    state: directory

- name: Unpack Maven Installation.
  unarchive:
    src: "{{ fetch_response.path }}"
    dest: "{{ mvn_install_dir }}" 
    extra_opts: [--strip-components=1]
    creates: "{{ mvn_install_dir }}/bin"
    remote_src: yes
