---
- name: Create groups.
  group:
    name: "{{ item.name }}"
    gid: "{{ item.gid }}"
  loop: "{{ users }}"

- name: Create users.
  user:
    name: "{{ item.name }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    uid: "{{ item.uid }}"
    group: "{{ item.name }}"
  loop: "{{ users }}"
