name: Packer Builds for thredds-test-action

on:
  workflow_dispatch:

jobs:
  packer-build:
    name: Build and publish Docker Image for thredds-test-action 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - uses: hashicorp/packer-github-actions@master
        with:
          command: init
          working_directory: .github/packer_files
          target: plugins.pkr.json
      - uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "--only=docker-github-action"
          working_directory: packer
          target: thredds-test-env.json
