name: Packer Builds for thredds-test-action

on:
  workflow_dispatch:
  pull_request:

jobs:
  packer-build:
    name: Build and publish Docker Image for thredds-test-action 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Execute Packer
        run: |
          cd packer
          packer build --only=docker-github-action \
            -var 'github.actor=${{ github.actor }}' \
            -var 'gha_token=${{ secrets.GITHUB_TOKEN }}' \
            thredds-test-env.json
