name: Packer Builds for thredds-test-action

on:
  workflow_dispatch:

jobs:
  packer-build:
    name: Build and publish Docker Image for thredds-test-action 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Execute Packer
        run: |
          cd packer
          packer plugins install github.com/hashicorp/docker
          packer build --only=docker-github-action thredds-test-env.json
          docker login --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} ghcr.io
          docker push ghcr.io/unidata/thredds-test-action:v2
          docker logout docker.pkg.github.com
