name: Packer Template Configuration Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  validate:
    name: Packer Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: latest
      - name: Run packer initi
        id: init
        run: "cd packer && packer init thredds-test-env.pkr.hcl"
      - name: Validate Template
        id: validate
        run: "cd packer && packer validate thredds-test-env.pkr.hcl"
